#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

gcloud container clusters get-credentials aggregator
kubectl delete secret tls-private-key || true
kubectl delete service aggregator || true
kubectl delete service metrics-sidecar -n agg-metrics || true
kubectl delete service aggregator-metrics -n agg-metrics || true 
kubectl delete service prometheus-k8s -n agg-metrics || true
kubectl delete pod aggregator || true 
kubectl delete deployment aggregator || true 
kubectl delete deployment metrics-to-stackdriver || true
kubectl delete deployment metrics-sidecar -n agg-metrics || true
