#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

gcloud container clusters get-credentials aggregator --zone=europe-west2-a
kubectl delete secret tls-private-key
kubectl delete service aggregator
kubectl delete service metrics-sidecar
kubectl delete service aggregator-metrics
kubectl delete pod aggregator
kubectl delete deployment aggregator
kubectl delete deployment metrics-to-stackdriver
kubectl delete deployment metrics-sidecar
